name: Extract ZIP file

on:
  push:
    paths:
      - 'sysarch lab act.zip'

jobs:
  extract-zip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install unzip utility
        run: sudo apt-get install unzip

      - name: Extract ZIP file
        run: unzip 'sysarch lab act.zip' -d extracted_files/

      - name: Commit extracted files
        run: |
          git add extracted_files/
          git commit -m "Extract zip file contents"
          git push

