name: Extract ZIP file

on:
  push:
    paths:
      - 'https://github.com/renz182003/graphql-movie-api/tree/main'

jobs:
  extract-zip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install unzip utility
        run: sudo apt-get install unzip

      - name: Extract ZIP file
        run: unzip path/to/your/file.zip -d extracted_files/

      - name: Commit extracted files
        run: |
          git add extracted_files/
          git commit -m "Extract zip file contents"
          git push

